[project]
name = "python"
version = "0.1.0"
description = "A project to mimic pod failed scenerio"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "psutil>=7.1.3",
    "uvicorn>=0.38.0",
]
